const { createClient } = require('@libsql/client');
const fs = require('fs');

const env = fs.readFileSync('.env.local', 'utf8');
for (const line of env.split('
')) {
  const m = line.match(/^([^#=]+)=(.*)$/);
  if (m) process.env[m[1].trim()] = m[2].trim();
}

const client = createClient({
  url: process.env.TURSO_DATABASE_URL,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

const segments = [
  { id: "seg_trend", name: "Trend-Driven Expressionists", description: "Fashion-forward individuals who follow nail trends closely and use nails as a form of self-expression and identity", age_focus: "18-28" },
  { id: "seg_busy", name: "Busy Professionals & Moms", description: "Time-poor women who want to look put-together without spending hours on nail maintenance", age_focus: "28-45" },
  { id: "seg_occasion", name: "Occasion & Event Seekers", description: "Women who want special nails for specific events like weddings, parties, or holidays", age_focus: "20-40" },
  { id: "seg_budget", name: "Budget-Conscious Beauty Lovers", description: "Value-seekers who love beauty but are price-sensitive and compare options carefully", age_focus: "18-35" },
  { id: "seg_natural", name: "Natural Nail Protectors", description: "Women who avoid traditional nail polish due to damage concerns and want healthy nail alternatives", age_focus: "25-45" },
  { id: "seg_new", name: "Press-On Newcomers", description: "Women who are new to press-on nails and need reassurance about quality, ease, and results", age_focus: "22-40" },
];

const personas = [
  { id: "per_trend_1", segment_id: "seg_trend", name: "The Aesthetic Curator", age: "19-24", motivation: "Wants nails that match her carefully crafted aesthetic and can be changed frequently to stay current", pain_point: "Salon visits are too slow and expensive to keep up with fast-changing trends", objection: "Press-ons look fake and basic compared to salon work", nail_preference: "Trendy sets: chrome, abstract art, 3D details, seasonal colors", trigger_message: "New drop: the exact nail set you saw on your FYP", creative_angle: "Aspirational visuals showing the nail set as part of a full aesthetic lifestyle", visual_world: "Flat lays, mood boards, aesthetic room setups, color-coordinated outfits", ad_formats: "Reels, TikTok videos, carousel posts, stories", what_not_to_show: "Plain or conservative nail styles; clinical before/after shots", tones: ["aspirational", "emotional"] },
  { id: "per_trend_2", segment_id: "seg_trend", name: "The Social Media Native", age: "18-22", motivation: "Uses nails as content - wants sets that photograph well and get engagement", pain_point: "Hard to find nails that look as good in photos as they do on screen", objection: "Not sure if press-ons will stay on long enough for a shoot or event", nail_preference: "Bold statement sets, unique textures, photo-ready designs", trigger_message: "The nails your followers will ask about", creative_angle: "Show the content creation process - nails in flat lay, holding phone, in mirror selfie", visual_world: "Ring lights, content creator setups, phone screens showing likes, aesthetic backdrops", ad_formats: "TikTok native content, Instagram reels, UGC-style videos", what_not_to_show: "Overly polished corporate-looking ads; nails that look too catalog", tones: ["aspirational", "curiosity"] },
  { id: "per_trend_3", segment_id: "seg_trend", name: "The Bold Experimenter", age: "20-27", motivation: "Wants to try daring styles without committing to permanent nail damage", pain_point: "Traditional nail polish chips quickly; gel is hard to remove and damages nails", objection: "Worried about the application process being too complicated", nail_preference: "Maximalist, avant-garde, experimental sets", trigger_message: "Try the trend. No commitment needed.", creative_angle: "Freedom and experimentation - before/after showing transformation without damage", visual_world: "Artistic photography, bold colors, creative lifestyle shots", ad_formats: "Transformation videos, before/after reels, tutorial content", what_not_to_show: "Boring or understated designs; anything that implies limitation", tones: ["curiosity", "contrast"] },
  { id: "per_busy_1", segment_id: "seg_busy", name: "The Corporate Professional", age: "28-38", motivation: "Wants polished, professional nails that last through a busy work week without maintenance", pain_point: "No time for salon appointments during the week; weekend appointments fill her schedule", objection: "Press-ons might look unprofessional or fall off at an important meeting", nail_preference: "Classic, clean designs: nude, French, subtle shimmer", trigger_message: "Professional nails in 10 minutes. No appointment needed.", creative_angle: "Time-saving focus - show application speed and professional result", visual_world: "Office settings, laptops, coffee cups, clean workspaces", ad_formats: "Quick tutorial videos, before/after stories, testimonials", what_not_to_show: "Overly decorative or casual nail styles; messy application processes", tones: ["benefit", "urgency"] },
  { id: "per_busy_2", segment_id: "seg_busy", name: "The Multitasking Mom", age: "30-42", motivation: "Wants to feel put-together and like herself again amid the chaos of motherhood", pain_point: "Self-care falls to the bottom of the priority list; salon time feels selfish", objection: "Press-ons will pop off during childcare tasks or while washing dishes", nail_preference: "Practical yet pretty: short to medium length, neutral to soft colors", trigger_message: "5 minutes. Beautiful nails. One less thing to worry about.", creative_angle: "Emotional - the small self-care moment that makes a big difference", visual_world: "Home environments, morning routines, relatable everyday moments", ad_formats: "Relatable video content, testimonials from moms, quick tutorial stories", what_not_to_show: "Overly glamorous lifestyles; long nails that imply fragility", tones: ["emotional", "benefit"] },
  { id: "per_busy_3", segment_id: "seg_busy", name: "The Always-On Entrepreneur", age: "27-40", motivation: "Values efficiency and quality - wants nails that represent her brand without wasting time", pain_point: "Every hour counts; traditional beauty routines feel like a poor investment of time", objection: "Skeptical about quality - has tried cheap press-ons before that looked and felt bad", nail_preference: "Sophisticated, intentional sets that signal success and taste", trigger_message: "High-quality nails on your schedule, not the salon.", creative_angle: "Premium efficiency - position Switch Nails as the smart choice for successful women", visual_world: "Minimal, high-end aesthetics; planning tools, brand environments, quality details", ad_formats: "Premium-looking video ads, LinkedIn-style content, quality-focused testimonials", what_not_to_show: "Budget-focused messaging; anything that implies compromise on quality", tones: ["benefit", "aspirational"] },
  { id: "per_occ_1", segment_id: "seg_occasion", name: "The Bride-to-Be", age: "24-35", motivation: "Wants perfect nails for her wedding day that photograph beautifully and last all day", pain_point: "Wedding nail appointments are expensive and hard to schedule; bridal nail fails are a real fear", objection: "Worried press-ons will not look natural enough for wedding photos", nail_preference: "Bridal sets: soft pink, French, pearl, elegant details", trigger_message: "Wedding-perfect nails you can rely on. No last-minute salon panic.", creative_angle: "Dream wedding aesthetic - nails as part of the perfect day", visual_world: "Wedding settings, bouquets, veils, soft natural lighting, detail shots", ad_formats: "Pinterest-style imagery, Instagram carousels, wedding content partnerships", what_not_to_show: "Bold or trendy styles; anything that looks temporary or casual", tones: ["aspirational", "emotional"] },
  { id: "per_occ_2", segment_id: "seg_occasion", name: "The Party Girl", age: "20-30", motivation: "Wants show-stopping nails for nights out, birthdays, and special events", pain_point: "Salon availability before events is unpredictable; last-minute nail emergencies are common", objection: "Worried nails will come off while dancing or during a long night out", nail_preference: "Glam, bold sets: rhinestones, holographic, party-ready designs", trigger_message: "Ready for the party in minutes. Nails that last all night.", creative_angle: "High-energy, fun, FOMO-inducing - the nails that complete the look", visual_world: "Party settings, night out photography, friends, celebration moments", ad_formats: "High-energy reels, before/after getting-ready content, event photography", what_not_to_show: "Subdued or professional settings; anything that feels low-energy", tones: ["urgency", "emotional"] },
  { id: "per_occ_3", segment_id: "seg_occasion", name: "The Holiday Dresser", age: "22-40", motivation: "Wants themed, seasonal nails that match holiday outfits and festive moments", pain_point: "Holiday-specific nail designs are only available for a short window and sell out fast", objection: "Not sure if seasonal designs are worth the investment for a short period", nail_preference: "Seasonal collections: holiday themes, festive colors, limited edition designs", trigger_message: "Limited edition holiday sets. Get them before they are gone.", creative_angle: "Scarcity and seasonal excitement - limited time, limited stock", visual_world: "Holiday settings, festive decorations, seasonal colors, gift-wrapped aesthetics", ad_formats: "Stories with countdown timers, seasonal email campaigns, limited drop announcements", what_not_to_show: "Everyday or generic designs; anything that undermines the special occasion feel", tones: ["urgency", "aspirational"] },
  { id: "per_bud_1", segment_id: "seg_budget", name: "The Value Seeker", age: "18-28", motivation: "Loves beauty but has a tight budget - needs to justify every purchase", pain_point: "Salon nails cost too much and chip within a week anyway", objection: "Press-ons seem like a waste of money if they fall off after a day", nail_preference: "Good-looking sets at a fair price; quality that matches the cost", trigger_message: "Salon-quality nails at a fraction of the price.", creative_angle: "Value comparison - cost per wear vs. salon price breakdown", visual_world: "Relatable everyday settings; shopping moments; practical lifestyle", ad_formats: "Comparison content, price-focused stories, testimonials emphasizing durability", what_not_to_show: "Luxury or aspirational imagery that feels out of reach", tones: ["benefit", "contrast"] },
